export default {
    BEGIN_EXECUTING: 'BEGIN_EXECUTING',
    COMPLETED_SUCCESSFULLY: 'COMPLETED_SUCCESSFULLY',
    COMPLETED_UNSUCCESSFULLY: 'COMPLETED_UNSUCCESSFULLY',
    MESSAGE_CHANGED: 'MESSAGE_CHANGED',
    STATE_CHANGED: 'STATE_CHANGED',
    RESULT_CHANGED: 'RESULT_CHANGED'
};